version: "3.8"
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"
    volumes:
      - erp_pg_data:/var/lib/postgresql/data

volumes:
  erp_pg_data:
